// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  CreateGeometryGeometryPostData,
  CreateGeometryGeometryPostErrors,
  CreateGeometryGeometryPostResponses,
  DeleteGeometryGeometryGeomIdDeleteData,
  DeleteGeometryGeometryGeomIdDeleteErrors,
  DeleteGeometryGeometryGeomIdDeleteResponses,
  GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetData,
  GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetErrors,
  GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetResponses,
  GetCensusBlockApiCensusBlockGetData,
  GetCensusBlockApiCensusBlockGetErrors,
  GetCensusBlockApiCensusBlockGetResponses,
  GetGeometryGeometryGeomIdGetData,
  GetGeometryGeometryGeomIdGetErrors,
  GetGeometryGeometryGeomIdGetResponses,
  ListGeometriesGeometryGetData,
  ListGeometriesGeometryGetResponses,
  RootGetData,
  RootGetResponses,
  UpdateGeometryGeometryGeomIdPutData,
  UpdateGeometryGeometryGeomIdPutErrors,
  UpdateGeometryGeometryGeomIdPutResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Get Census Block
 */
export const getCensusBlockApiCensusBlockGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCensusBlockApiCensusBlockGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetCensusBlockApiCensusBlockGetResponses,
    GetCensusBlockApiCensusBlockGetErrors,
    ThrowOnError
  >({
    url: '/api/census/block',
    ...options,
  })
}

/**
 * List Geometries
 */
export const listGeometriesGeometryGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListGeometriesGeometryGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListGeometriesGeometryGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/geometry/',
    ...options,
  })
}

/**
 * Create Geometry
 */
export const createGeometryGeometryPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateGeometryGeometryPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateGeometryGeometryPostResponses,
    CreateGeometryGeometryPostErrors,
    ThrowOnError
  >({
    url: '/geometry/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Delete Geometry
 */
export const deleteGeometryGeometryGeomIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteGeometryGeometryGeomIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteGeometryGeometryGeomIdDeleteResponses,
    DeleteGeometryGeometryGeomIdDeleteErrors,
    ThrowOnError
  >({
    url: '/geometry/{geom_id}',
    ...options,
  })
}

/**
 * Get Geometry
 */
export const getGeometryGeometryGeomIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetGeometryGeometryGeomIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetGeometryGeometryGeomIdGetResponses,
    GetGeometryGeometryGeomIdGetErrors,
    ThrowOnError
  >({
    url: '/geometry/{geom_id}',
    ...options,
  })
}

/**
 * Update Geometry
 */
export const updateGeometryGeometryGeomIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateGeometryGeometryGeomIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateGeometryGeometryGeomIdPutResponses,
    UpdateGeometryGeometryGeomIdPutErrors,
    ThrowOnError
  >({
    url: '/geometry/{geom_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Carbon Mapper Plumes
 *
 * Proxy endpoint to Carbon Mapper API.
 * Uses CARBON_MAPPER_TOKEN from environment variables for secure authentication.
 */
export const getCarbonMapperPlumesApiV1CarbonMapperPlumesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetResponses,
    GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetErrors,
    ThrowOnError
  >({
    url: '/api/v1/carbon-mapper/plumes',
    ...options,
  })
}

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    RootGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/',
    ...options,
  })
}
