// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://arcgis-playground-api.onrender.com' | (string & {})
}

/**
 * CarbonMapperPlume
 */
export type CarbonMapperPlume = {
  /**
   * Id
   */
  id: string
  /**
   * Plume Id
   */
  plume_id?: string | null
  /**
   * Gas
   */
  gas?: string | null
  /**
   * Geometry Json
   */
  geometry_json?: unknown | null
  /**
   * Plume Bounds
   */
  plume_bounds?: Array<number> | null
  /**
   * Plume Png
   */
  plume_png?: string | null
  /**
   * Emission Auto
   */
  emission_auto?: number | null
  /**
   * Platform
   */
  platform?: string | null
  /**
   * Instrument
   */
  instrument?: string | null
  /**
   * Scene Timestamp
   */
  scene_timestamp?: string | null
}

/**
 * CarbonMapperResponse
 */
export type CarbonMapperResponse = {
  /**
   * Items
   */
  items: Array<CarbonMapperPlume>
  /**
   * Total Count
   */
  total_count?: number | null
  /**
   * Bbox Count
   */
  bbox_count?: number | null
  /**
   * Limit
   */
  limit?: number | null
  /**
   * Offset
   */
  offset?: number | null
}

/**
 * CensusBlockResponse
 */
export type CensusBlockResponse = {
  /**
   * Geoid
   */
  geoid: string
  /**
   * State
   */
  state: string
  /**
   * County
   */
  county: string
  /**
   * Tract
   */
  tract: string
  /**
   * Block
   */
  block: string
  /**
   * Bbox
   */
  bbox: Array<number> | null
  geometry: CensusGeometry
}

/**
 * CensusGeometry
 */
export type CensusGeometry = {
  /**
   * Rings
   */
  rings: Array<Array<Array<number>>>
  /**
   * Spatialreference
   */
  spatialReference?: {
    [key: string]: unknown
  } | null
}

/**
 * GeometryCreate
 */
export type GeometryCreate = {
  /**
   * Label
   */
  label?: string | null
  /**
   * Wkt
   */
  wkt: string
}

/**
 * GeometryRead
 */
export type GeometryRead = {
  /**
   * Label
   */
  label?: string | null
  /**
   * Wkt
   */
  wkt: string
  /**
   * Id
   */
  id: number
}

/**
 * GeometryUpdate
 */
export type GeometryUpdate = {
  /**
   * Label
   */
  label?: string | null
  /**
   * Wkt
   */
  wkt?: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type GetCensusBlockApiCensusBlockGetData = {
  body?: never
  path?: never
  query: {
    /**
     * Lat
     */
    lat: number
    /**
     * Lng
     */
    lng: number
  }
  url: '/api/census/block'
}

export type GetCensusBlockApiCensusBlockGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetCensusBlockApiCensusBlockGetError =
  GetCensusBlockApiCensusBlockGetErrors[keyof GetCensusBlockApiCensusBlockGetErrors]

export type GetCensusBlockApiCensusBlockGetResponses = {
  /**
   * Successful Response
   */
  200: CensusBlockResponse
}

export type GetCensusBlockApiCensusBlockGetResponse =
  GetCensusBlockApiCensusBlockGetResponses[keyof GetCensusBlockApiCensusBlockGetResponses]

export type ListGeometriesGeometryGetData = {
  body?: never
  path?: never
  query?: never
  url: '/geometry/'
}

export type ListGeometriesGeometryGetResponses = {
  /**
   * Response List Geometries Geometry  Get
   *
   * Successful Response
   */
  200: Array<GeometryRead>
}

export type ListGeometriesGeometryGetResponse =
  ListGeometriesGeometryGetResponses[keyof ListGeometriesGeometryGetResponses]

export type CreateGeometryGeometryPostData = {
  body: GeometryCreate
  path?: never
  query?: never
  url: '/geometry/'
}

export type CreateGeometryGeometryPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateGeometryGeometryPostError =
  CreateGeometryGeometryPostErrors[keyof CreateGeometryGeometryPostErrors]

export type CreateGeometryGeometryPostResponses = {
  /**
   * Successful Response
   */
  200: GeometryRead
}

export type CreateGeometryGeometryPostResponse =
  CreateGeometryGeometryPostResponses[keyof CreateGeometryGeometryPostResponses]

export type DeleteGeometryGeometryGeomIdDeleteData = {
  body?: never
  path: {
    /**
     * Geom Id
     */
    geom_id: number
  }
  query?: never
  url: '/geometry/{geom_id}'
}

export type DeleteGeometryGeometryGeomIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteGeometryGeometryGeomIdDeleteError =
  DeleteGeometryGeometryGeomIdDeleteErrors[keyof DeleteGeometryGeometryGeomIdDeleteErrors]

export type DeleteGeometryGeometryGeomIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetGeometryGeometryGeomIdGetData = {
  body?: never
  path: {
    /**
     * Geom Id
     */
    geom_id: number
  }
  query?: never
  url: '/geometry/{geom_id}'
}

export type GetGeometryGeometryGeomIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetGeometryGeometryGeomIdGetError =
  GetGeometryGeometryGeomIdGetErrors[keyof GetGeometryGeometryGeomIdGetErrors]

export type GetGeometryGeometryGeomIdGetResponses = {
  /**
   * Successful Response
   */
  200: GeometryRead
}

export type GetGeometryGeometryGeomIdGetResponse =
  GetGeometryGeometryGeomIdGetResponses[keyof GetGeometryGeometryGeomIdGetResponses]

export type UpdateGeometryGeometryGeomIdPutData = {
  body: GeometryUpdate
  path: {
    /**
     * Geom Id
     */
    geom_id: number
  }
  query?: never
  url: '/geometry/{geom_id}'
}

export type UpdateGeometryGeometryGeomIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateGeometryGeometryGeomIdPutError =
  UpdateGeometryGeometryGeomIdPutErrors[keyof UpdateGeometryGeometryGeomIdPutErrors]

export type UpdateGeometryGeometryGeomIdPutResponses = {
  /**
   * Successful Response
   */
  200: GeometryRead
}

export type UpdateGeometryGeometryGeomIdPutResponse =
  UpdateGeometryGeometryGeomIdPutResponses[keyof UpdateGeometryGeometryGeomIdPutResponses]

export type GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Instrument
     */
    instrument?: string | null
    /**
     * Country
     */
    country?: string | null
    /**
     * Plume Id
     */
    plume_id?: string | null
    /**
     * Collection Date Start
     */
    collection_date_start?: string | null
    /**
     * Collection Date End
     */
    collection_date_end?: string | null
  }
  url: '/api/v1/carbon-mapper/plumes'
}

export type GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetError =
  GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetErrors[keyof GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetErrors]

export type GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetResponses = {
  /**
   * Successful Response
   */
  200: CarbonMapperResponse
}

export type GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetResponse =
  GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetResponses[keyof GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetResponses]

export type RootGetData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
