// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query'

import { client } from '../client.gen'
import {
  createGeometryGeometryPost,
  deleteGeometryGeometryGeomIdDelete,
  getCarbonMapperPlumesApiV1CarbonMapperPlumesGet,
  getCensusBlockApiCensusBlockGet,
  getGeometryGeometryGeomIdGet,
  listGeometriesGeometryGet,
  type Options,
  rootGet,
  updateGeometryGeometryGeomIdPut,
} from '../sdk.gen'
import type {
  CreateGeometryGeometryPostData,
  CreateGeometryGeometryPostError,
  CreateGeometryGeometryPostResponse,
  DeleteGeometryGeometryGeomIdDeleteData,
  DeleteGeometryGeometryGeomIdDeleteError,
  GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetData,
  GetCensusBlockApiCensusBlockGetData,
  GetGeometryGeometryGeomIdGetData,
  ListGeometriesGeometryGetData,
  RootGetData,
  UpdateGeometryGeometryGeomIdPutData,
  UpdateGeometryGeometryGeomIdPutError,
  UpdateGeometryGeometryGeomIdPutResponse,
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getCensusBlockApiCensusBlockGetQueryKey = (
  options: Options<GetCensusBlockApiCensusBlockGetData>,
) => createQueryKey('getCensusBlockApiCensusBlockGet', options)

/**
 * Get Census Block
 */
export const getCensusBlockApiCensusBlockGetOptions = (
  options: Options<GetCensusBlockApiCensusBlockGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCensusBlockApiCensusBlockGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCensusBlockApiCensusBlockGetQueryKey(options),
  })
}

export const listGeometriesGeometryGetQueryKey = (
  options?: Options<ListGeometriesGeometryGetData>,
) => createQueryKey('listGeometriesGeometryGet', options)

/**
 * List Geometries
 */
export const listGeometriesGeometryGetOptions = (
  options?: Options<ListGeometriesGeometryGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listGeometriesGeometryGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listGeometriesGeometryGetQueryKey(options),
  })
}

/**
 * Create Geometry
 */
export const createGeometryGeometryPostMutation = (
  options?: Partial<Options<CreateGeometryGeometryPostData>>,
): UseMutationOptions<
  CreateGeometryGeometryPostResponse,
  CreateGeometryGeometryPostError,
  Options<CreateGeometryGeometryPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateGeometryGeometryPostResponse,
    CreateGeometryGeometryPostError,
    Options<CreateGeometryGeometryPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createGeometryGeometryPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Geometry
 */
export const deleteGeometryGeometryGeomIdDeleteMutation = (
  options?: Partial<Options<DeleteGeometryGeometryGeomIdDeleteData>>,
): UseMutationOptions<
  unknown,
  DeleteGeometryGeometryGeomIdDeleteError,
  Options<DeleteGeometryGeometryGeomIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteGeometryGeometryGeomIdDeleteError,
    Options<DeleteGeometryGeometryGeomIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteGeometryGeometryGeomIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getGeometryGeometryGeomIdGetQueryKey = (
  options: Options<GetGeometryGeometryGeomIdGetData>,
) => createQueryKey('getGeometryGeometryGeomIdGet', options)

/**
 * Get Geometry
 */
export const getGeometryGeometryGeomIdGetOptions = (
  options: Options<GetGeometryGeometryGeomIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGeometryGeometryGeomIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getGeometryGeometryGeomIdGetQueryKey(options),
  })
}

/**
 * Update Geometry
 */
export const updateGeometryGeometryGeomIdPutMutation = (
  options?: Partial<Options<UpdateGeometryGeometryGeomIdPutData>>,
): UseMutationOptions<
  UpdateGeometryGeometryGeomIdPutResponse,
  UpdateGeometryGeometryGeomIdPutError,
  Options<UpdateGeometryGeometryGeomIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateGeometryGeometryGeomIdPutResponse,
    UpdateGeometryGeometryGeomIdPutError,
    Options<UpdateGeometryGeometryGeomIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateGeometryGeometryGeomIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getCarbonMapperPlumesApiV1CarbonMapperPlumesGetQueryKey = (
  options?: Options<GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetData>,
) => createQueryKey('getCarbonMapperPlumesApiV1CarbonMapperPlumesGet', options)

/**
 * Get Carbon Mapper Plumes
 *
 * Proxy endpoint to Carbon Mapper API.
 * Uses CARBON_MAPPER_TOKEN from environment variables for secure authentication.
 */
export const getCarbonMapperPlumesApiV1CarbonMapperPlumesGetOptions = (
  options?: Options<GetCarbonMapperPlumesApiV1CarbonMapperPlumesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCarbonMapperPlumesApiV1CarbonMapperPlumesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCarbonMapperPlumesApiV1CarbonMapperPlumesGetQueryKey(options),
  })
}

export const rootGetQueryKey = (options?: Options<RootGetData>) =>
  createQueryKey('rootGet', options)

/**
 * Root
 */
export const rootGetOptions = (options?: Options<RootGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await rootGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: rootGetQueryKey(options),
  })
}
